---
development:
  dialect: postgres
  database: sharaphka
  user: postgres
  password: password
  host: 192.168.80.3
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/sharaphka_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/sharaphka_production?sslmode=disable"}}
